# Generated by Django 2.2 on 2019-12-22 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('style', models.CharField(default='Style', max_length=255)),
                ('description', models.TextField(default='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProductManager.Product')),
                ('diameter', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('BLACK', 'black'), ('SILVER', 'silver'), ('GRAY', 'gray'), ('GOLD', 'gold'), ('ROSE GOLD', 'rose gold'), ('BRONZE', 'bronze'), ('COPPER', 'copper'), ('WHITE', 'white'), ('DARK RED', 'dark red'), ('RED', 'red'), ('PURPLE', 'purple'), ('PINK', 'pink'), ('GREEN', 'green'), ('NEON GREEN', 'neon green'), ('ARMY GREEN', 'army green'), ('YELLOW', 'yellow'), ('DARK BLUE', 'dark blue'), ('SEA GREEN', 'sea green'), ('SEA BLUE', 'sea blue')], max_length=255)),
                ('finish', models.CharField(choices=[('MATTE', 'matte'), ('SATIN', 'satin'), ('GLOSS', 'gloss'), ('MIRROR', 'mirror'), ('MILLED', 'milled')], max_length=255)),
            ],
            bases=('ProductManager.product',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProductManager.Product')),
                ('Austell', models.IntegerField(default=0)),
                ('Alpharetta', models.IntegerField(default=0)),
                ('Buckhead', models.IntegerField(default=0)),
                ('Marietta', models.IntegerField(default=0)),
            ],
            bases=('ProductManager.product',),
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ProductManager.Location')),
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProductManager.Attribute')),
                ('sku', models.SlugField(default='1')),
            ],
            bases=('ProductManager.attribute', 'ProductManager.location'),
        ),
    ]
